name: Release NX App to k8s

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        description: the name of the image to build
        required: true
      application_dll:
        type: string
        description: the name of the dll to run
        required: true
      environment:
        type: string
        description: environment to deploy to
        required: true
      deploy_to_restart:
        type: string
        description: the name of the deployment to restart
        required: false
    secrets:
      ZEROTIER_NETWORK_ID:
        required: true
      ZEROTIER_CENTRAL_TOKEN:
        required: true
      DOCKER_REGISTRY_NAME:
        required: true
      KUBE_CONFIG:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: artificial-scrum-master-binaries
        path: ./dist

    - name: Copy Dockerfile
      run: cp ./artificial-scrum-master/Dockerfile .

    - name: ZeroTier
      uses: zerotier/github-action@v1
      with:
        network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
        auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Insecure Docker Repository
      run: |
        sudo truncate -s-2 /etc/docker/daemon.json
        echo ", \"insecure-registries\": [\"${{ secrets.DOCKER_REGISTRY_NAME }}\"]}" | sudo tee -a /etc/docker/daemon.json
        sudo systemctl restart docker
      
    - name: Build and push to local registry
      run: |
        docker build --build-arg DLL_TO_RUN=${{inputs.application_dll}} -t ${{ secrets.DOCKER_REGISTRY_NAME }}/${{inputs.image_name}}:latest .
        docker push ${{ secrets.DOCKER_REGISTRY_NAME }}/${{inputs.image_name}}:latest
    
    - name: Restart pods
      if: ${{ inputs.deploy_to_restart }}
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout restart deploy ${{inputs.deploy_to_restart}} --namespace scrum-master