name: Release Artificial Scrum Master

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-nx-app.yml

  release-eris:
    needs: build
    uses: ./.github/workflows/release-env.yml
    secrets:
      env: 'eris'