name: Release Artificial Scrum Master

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-nx-app.yml
    secrets:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

  release-eris:
    needs: build
    uses: ./.github/workflows/release-env.yml
    with:
      environment: 'eris'
    secrets:
      ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
      ZEROTIER_CENTRAL_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      DOCKER_REGISTRY_NAME: ${{ secrets.DOCKER_REGISTRY_NAME }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  release-roxy:
    needs: build
    uses: ./.github/workflows/release-env.yml
    with:
      environment: 'roxy'
    secrets:
      ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
      ZEROTIER_CENTRAL_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      DOCKER_REGISTRY_NAME: ${{ secrets.DOCKER_REGISTRY_NAME }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
