name: Release Artificial Scrum Master

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-nx-app.yml
    secrets:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

  release-eris:
    needs: build
    uses: ./.github/workflows/release-env.yml
    with:
      environment: 'eris'
      dockerfile_name: 'DockerfileApp'
      image_name: 'artificial-scrum-master'
      deploy_to_restart: 'ai-scrum-master-deploy'
      artifact_name: 'artificial-scrum-master-binaries'
    secrets:
      ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
      ZEROTIER_CENTRAL_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      DOCKER_REGISTRY_NAME: ${{ secrets.DOCKER_REGISTRY_NAME }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  release-roxy:
    needs: build
    uses: ./.github/workflows/release-env.yml
    with:
      environment: 'roxy'
      dockerfile_name: 'DockerfileApp'
      image_name: 'artificial-scrum-master'
      deploy_to_restart: 'ai-scrum-master-deploy'
      artifact_name: 'artificial-scrum-master-binaries'
    secrets:
      ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
      ZEROTIER_CENTRAL_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      DOCKER_REGISTRY_NAME: ${{ secrets.DOCKER_REGISTRY_NAME }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  release-production:
    needs: release-eris
    runs-on: ubuntu-latest
    environment:
      name: 'production'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artificial-scrum-master-binaries
          path: ./dist

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist
