name: Release Artificial Scrum Master

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./artificial-scrum-master

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '21.1'

    - name: Install dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: npm install

    - name: Test dotnet app
      run: dotnet test apps/artificial.scrum.master
    
    - name: Test frontend
      run: npx nx test artificial.scrum.master.frontend

    - name: Build dotnet app
      run: npx nx build artificial.scrum.master

    - name: Build frontend
      run: npx nx build artificial.scrum.master.frontend --configuration=production

    - name: Copy frontend
      run: cp -r ./dist/apps/artificial.scrum.master.frontend/browser ./dist/apps/artificial.scrum.master/Artificial.Scrum.Master/net8.0/wwwroot

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: artificial-scrum-master-binaries
        path: ./artificial-scrum-master/dist/apps/artificial.scrum.master/Artificial.Scrum.Master/net8.0
        retention-days: 1

  release-eris:
    needs: build
    runs-on: ubuntu-latest
    environment: 'eris'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: artificial-scrum-master-binaries
        path: ./dist

    - name: Copy Dockerfile
      run: cp ./artificial-scrum-master/Dockerfile .

    - name: ZeroTier
      uses: zerotier/github-action@v1
      with:
        network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        config-inline: |
          [registry."172.28.0.4:5000"]
          http = true
          insecure = true

      
    - name: Build and push to local registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: 172.28.0.4:5000/artificialscrummaster:latest
